PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX schema: <http://www.schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

 SELECT DISTINCT ?year ?decade WHERE {
   $paramArtist wdt:P571 ?queryYear.
   ?band wdt:P571 ?year.
   ?band wdt:P1902 ?spotifyID.
   ?band rdfs:label ?bandLabel.
   FILTER((LANG(?bandLabel)) = "de" && ( 10 * (xsd:integer(YEAR(?year) / 10))) = ( 10 * (xsd:integer(YEAR(?queryYear) / 10))))
   bind( ( 10 * (xsd:integer(YEAR(?year) / 10))) as ?decade )
 }